# Project-wide Gradle settings
# https://developer.android.com/studio/build/gradle-tips

# Build performance
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# R class
android.nonTransitiveRClass=true

# Compose
android.enableJetifier=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
